"""refactor_consumption_and_wastage_unified

Revision ID: 019121aef244
Revises: bbdc6705d10f
Create Date: 2026-05-08 22:02:29.016528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '019121aef244'
down_revision: Union[str, Sequence[str], None] = 'bbdc6705d10f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consumption_entries', sa.Column('total_cooking_persons', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('consumption_entries', sa.Column('total_cleaning_persons', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('consumption_entries', sa.Column('total_serving_persons', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.drop_constraint(op.f('fk_consumption_entries_financial_year'), 'consumption_entries', type_='foreignkey')
    op.drop_column('consumption_entries', 'payas_remained')
    op.drop_column('consumption_entries', 'saru_remained')
    op.drop_column('consumption_entries', 'huli_remained')
    op.drop_column('consumption_entries', 'anna_remained')
    op.drop_constraint(op.f('fk_daily_stock_summary_financial_year'), 'daily_stock_summary', type_='foreignkey')
    op.drop_constraint(op.f('fk_item_categories_financial_year'), 'item_categories', type_='foreignkey')
    op.drop_constraint(op.f('fk_item_types_financial_year'), 'item_types', type_='foreignkey')
    op.drop_constraint(op.f('fk_items_financial_year'), 'items', type_='foreignkey')
    op.drop_constraint(op.f('fk_menu_items_financial_year'), 'menu_items', type_='foreignkey')
    op.drop_constraint(op.f('fk_monthly_stock_summary_financial_year'), 'monthly_stock_summary', type_='foreignkey')
    op.drop_constraint(op.f('fk_purchase_entries_financial_year'), 'purchase_entries', type_='foreignkey')
    op.drop_constraint(op.f('fk_stock_adjustments_financial_year'), 'stock_adjustments', type_='foreignkey')
    op.drop_constraint(op.f('fk_stock_ledger_financial_year'), 'stock_ledger', type_='foreignkey')
    op.drop_constraint(op.f('fk_token_generations_financial_year'), 'token_generations', type_='foreignkey')
    op.drop_constraint(op.f('fk_units_financial_year'), 'units', type_='foreignkey')
    op.drop_constraint(op.f('fk_vendor_payments_financial_year'), 'vendor_payments', type_='foreignkey')
    op.drop_constraint(op.f('fk_vendors_financial_year'), 'vendors', type_='foreignkey')
    op.drop_constraint(op.f('fk_wastage_entries_financial_year'), 'wastage_entries', type_='foreignkey')
    op.add_column('wastage_items', sa.Column('consumption_entry_id', sa.Integer(), nullable=True))
    op.alter_column('wastage_items', 'wastage_entry_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'wastage_items', 'consumption_entries', ['consumption_entry_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wastage_items', type_='foreignkey')
    op.alter_column('wastage_items', 'wastage_entry_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('wastage_items', 'consumption_entry_id')
    op.create_foreign_key(op.f('fk_wastage_entries_financial_year'), 'wastage_entries', 'financial_years', ['financial_year_id'], ['id'])
    op.create_foreign_key(op.f('fk_vendors_financial_year'), 'vendors', 'financial_years', ['financial_year_id'], ['id'])
    op.create_foreign_key(op.f('fk_vendor_payments_financial_year'), 'vendor_payments', 'financial_years', ['financial_year_id'], ['id'])
    op.create_foreign_key(op.f('fk_units_financial_year'), 'units', 'financial_years', ['financial_year_id'], ['id'])
    op.create_foreign_key(op.f('fk_token_generations_financial_year'), 'token_generations', 'financial_years', ['financial_year_id'], ['id'])
    op.create_foreign_key(op.f('fk_stock_ledger_financial_year'), 'stock_ledger', 'financial_years', ['financial_year_id'], ['id'])
    op.create_foreign_key(op.f('fk_stock_adjustments_financial_year'), 'stock_adjustments', 'financial_years', ['financial_year_id'], ['id'])
    op.create_foreign_key(op.f('fk_purchase_entries_financial_year'), 'purchase_entries', 'financial_years', ['financial_year_id'], ['id'])
    op.create_foreign_key(op.f('fk_monthly_stock_summary_financial_year'), 'monthly_stock_summary', 'financial_years', ['financial_year_id'], ['id'])
    op.create_foreign_key(op.f('fk_menu_items_financial_year'), 'menu_items', 'financial_years', ['financial_year_id'], ['id'])
    op.create_foreign_key(op.f('fk_items_financial_year'), 'items', 'financial_years', ['financial_year_id'], ['id'])
    op.create_foreign_key(op.f('fk_item_types_financial_year'), 'item_types', 'financial_years', ['financial_year_id'], ['id'])
    op.create_foreign_key(op.f('fk_item_categories_financial_year'), 'item_categories', 'financial_years', ['financial_year_id'], ['id'])
    op.create_foreign_key(op.f('fk_daily_stock_summary_financial_year'), 'daily_stock_summary', 'financial_years', ['financial_year_id'], ['id'])
    op.add_column('consumption_entries', sa.Column('anna_remained', sa.NUMERIC(precision=15, scale=3), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('consumption_entries', sa.Column('huli_remained', sa.NUMERIC(precision=15, scale=3), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('consumption_entries', sa.Column('saru_remained', sa.NUMERIC(precision=15, scale=3), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('consumption_entries', sa.Column('payas_remained', sa.NUMERIC(precision=15, scale=3), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_consumption_entries_financial_year'), 'consumption_entries', 'financial_years', ['financial_year_id'], ['id'])
    op.drop_column('consumption_entries', 'total_serving_persons')
    op.drop_column('consumption_entries', 'total_cleaning_persons')
    op.drop_column('consumption_entries', 'total_cooking_persons')
    # ### end Alembic commands ###
