"""add_consumption_entry_id_to_wastage

Revision ID: 067ac375f988
Revises: ee812d4dd204
Create Date: 2026-05-09 22:12:04.482978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '067ac375f988'
down_revision: Union[str, Sequence[str], None] = 'ee812d4dd204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wastage_entries', sa.Column('consumption_entry_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'wastage_entries', 'consumption_entries', ['consumption_entry_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wastage_entries', type_='foreignkey')
    op.drop_column('wastage_entries', 'consumption_entry_id')
    # ### end Alembic commands ###
