"""Sync user removals and updates

Revision ID: 1e22e038a432
Revises: b1c2d3e4f5a6
Create Date: 2026-06-17 22:57:58.658722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e22e038a432'
down_revision: Union[str, Sequence[str], None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Safely handle vendor_payments removal
    # Check if table exists before dropping (for idempotency)
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'vendor_payments' in tables:
        op.drop_index(op.f('ix_vendor_payments_payment_date'), table_name='vendor_payments')
        op.drop_index(op.f('ix_vendor_payments_status'), table_name='vendor_payments')
        op.drop_index(op.f('ix_vendor_payments_user_id'), table_name='vendor_payments')
        op.drop_index(op.f('ix_vendor_payments_vendor_id'), table_name='vendor_payments')
        op.drop_table('vendor_payments')

    # Drop unique constraints on receipt_sequences that the user removed from models
    op.drop_index('uq_receipt_sequences_donation_scope', table_name='receipt_sequences', postgresql_where='(donation_type_id IS NOT NULL)')
    op.drop_index('uq_receipt_sequences_general_scope', table_name='receipt_sequences', postgresql_where='(donation_type_id IS NULL)')
    
    # NOTE: We are NOT dropping token_details partitions here. 
    # Even though they aren't in the models, they are managed by the database partitioning logic.
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_receipt_sequences_general_scope', 'receipt_sequences', ['financial_year_id', 'sequence_type'], unique=True, postgresql_where='(donation_type_id IS NULL)')
    op.create_index('uq_receipt_sequences_donation_scope', 'receipt_sequences', ['financial_year_id', 'sequence_type', 'donation_type_id'], unique=True, postgresql_where='(donation_type_id IS NOT NULL)')
    
    op.create_table('vendor_payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('payment_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('vendor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=15, scale=3), autoincrement=False, nullable=False),
    sa.Column('payment_mode', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('reference_no', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint('amount >= 0::numeric', name='ck_vendor_payments_amount_non_negative'),
    sa.CheckConstraint('status = ANY (ARRAY[0, 1])', name='ck_vendor_payments_status_binary'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='vendor_payments_created_by_fkey'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='vendor_payments_updated_by_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='vendor_payments_user_id_fkey'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name='vendor_payments_vendor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='vendor_payments_pkey')
    )
    op.create_index('ix_vendor_payments_vendor_id', 'vendor_payments', ['vendor_id'], unique=False)
    op.create_index('ix_vendor_payments_user_id', 'vendor_payments', ['user_id'], unique=False)
    op.create_index('ix_vendor_payments_status', 'vendor_payments', ['status'], unique=False)
    op.create_index('ix_vendor_payments_payment_date', 'vendor_payments', ['payment_date'], unique=False)
    # ### end Alembic commands ###
