"""add_consumption_entry_id_to_stock_adjustments

Revision ID: 2fcdeda76a9a
Revises: 60deefdc3e82
Create Date: 2026-05-14 00:41:05.475177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2fcdeda76a9a'
down_revision: Union[str, Sequence[str], None] = '60deefdc3e82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_adjustments', sa.Column('consumption_entry_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stock_adjustments', 'consumption_entries', ['consumption_entry_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_adjustments', type_='foreignkey')
    op.drop_column('stock_adjustments', 'consumption_entry_id')
    # ### end Alembic commands ###
