"""change_stock_fields_to_string

Revision ID: 349755408b19
Revises: d12f8c4a9b21
Create Date: 2026-05-07 00:01:51.013045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '349755408b19'
down_revision: Union[str, Sequence[str], None] = 'd12f8c4a9b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_details_2026_09')
    op.drop_table('token_details_2026_10')
    op.drop_table('token_details_2027_10')
    op.drop_table('token_details_2026_05')
    op.drop_table('token_details_2026_04')
    op.drop_table('token_details_2026_07')
    op.drop_table('token_details_2026_06')
    op.drop_table('token_details_2026_03')
    op.drop_table('token_details_2027_05')
    op.drop_table('token_details_2027_03')
    op.drop_table('token_details_2027_09')
    op.drop_table('token_details_2027_12')
    op.drop_table('token_details_2026_08')
    op.drop_table('token_details_2026_02')
    op.drop_table('token_details_2027_08')
    op.drop_table('token_details_2026_12')
    op.drop_table('token_details_2027_01')
    op.drop_table('token_details_2027_06')
    op.drop_table('token_details_2027_07')
    op.drop_table('token_details_2027_11')
    op.drop_table('token_details_2027_04')
    op.drop_table('token_details_2027_02')
    op.drop_table('token_details_2026_11')
    op.drop_table('token_details_2026_01')
    op.drop_index(op.f('idx_activity_logs_meta_gin'), table_name='activity_logs', postgresql_using='gin')
    op.drop_index(op.f('idx_activity_logs_route_template_activity_at'), table_name='activity_logs')
    op.drop_index(op.f('idx_activity_logs_status_activity_at'), table_name='activity_logs')
    op.drop_index(op.f('idx_activity_logs_user_id_activity_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_activity_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_endpoint'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_item_categories_type_id'), table_name='item_categories')
    op.alter_column('items', 'opening_stock',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('items', 'current_stock',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'current_stock',
               existing_type=sa.String(length=50),
               type_=sa.NUMERIC(precision=15, scale=3),
               existing_nullable=False)
    op.alter_column('items', 'opening_stock',
               existing_type=sa.String(length=50),
               type_=sa.NUMERIC(precision=15, scale=3),
               existing_nullable=False)
    op.create_index(op.f('ix_item_categories_type_id'), 'item_categories', ['type_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_endpoint'), 'activity_logs', ['endpoint'], unique=False)
    op.create_index(op.f('ix_activity_logs_activity_at'), 'activity_logs', ['activity_at'], unique=False)
    op.create_index(op.f('idx_activity_logs_user_id_activity_at'), 'activity_logs', ['user_id', 'activity_at'], unique=False)
    op.create_index(op.f('idx_activity_logs_status_activity_at'), 'activity_logs', ['activity_status', 'activity_at'], unique=False)
    op.create_index(op.f('idx_activity_logs_route_template_activity_at'), 'activity_logs', ['route_template', 'activity_at'], unique=False)
    op.create_index(op.f('idx_activity_logs_meta_gin'), 'activity_logs', ['meta'], unique=False, postgresql_using='gin')
    op.create_table('token_details_2026_01',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_01_pkey'))
    )
    op.create_table('token_details_2026_11',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_11_pkey'))
    )
    op.create_table('token_details_2027_02',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_02_pkey'))
    )
    op.create_table('token_details_2027_04',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_04_pkey'))
    )
    op.create_table('token_details_2027_11',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_11_pkey'))
    )
    op.create_table('token_details_2027_07',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_07_pkey'))
    )
    op.create_table('token_details_2027_06',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_06_pkey'))
    )
    op.create_table('token_details_2027_01',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_01_pkey'))
    )
    op.create_table('token_details_2026_12',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_12_pkey'))
    )
    op.create_table('token_details_2027_08',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_08_pkey'))
    )
    op.create_table('token_details_2026_02',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_02_pkey'))
    )
    op.create_table('token_details_2026_08',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_08_pkey'))
    )
    op.create_table('token_details_2027_12',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_12_pkey'))
    )
    op.create_table('token_details_2027_09',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_09_pkey'))
    )
    op.create_table('token_details_2027_03',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_03_pkey'))
    )
    op.create_table('token_details_2027_05',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_05_pkey'))
    )
    op.create_table('token_details_2026_03',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_03_pkey'))
    )
    op.create_table('token_details_2026_06',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_06_pkey'))
    )
    op.create_table('token_details_2026_07',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_07_pkey'))
    )
    op.create_table('token_details_2026_04',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_04_pkey'))
    )
    op.create_table('token_details_2026_05',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_05_pkey'))
    )
    op.create_table('token_details_2027_10',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_10_pkey'))
    )
    op.create_table('token_details_2026_10',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_10_pkey'))
    )
    op.create_table('token_details_2026_09',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_09_pkey'))
    )
    # ### end Alembic commands ###
