"""change_stock_fields_to_string

Revision ID: 349755408b19
Revises: d12f8c4a9b21
Create Date: 2026-05-07 00:01:51.013045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '349755408b19'
down_revision: Union[str, Sequence[str], None] = 'd12f8c4a9b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_activity_logs_meta_gin'), table_name='activity_logs', postgresql_using='gin')
    op.drop_index(op.f('idx_activity_logs_route_template_activity_at'), table_name='activity_logs')
    op.drop_index(op.f('idx_activity_logs_status_activity_at'), table_name='activity_logs')
    op.drop_index(op.f('idx_activity_logs_user_id_activity_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_activity_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_endpoint'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_item_categories_type_id'), table_name='item_categories')
    op.alter_column('items', 'opening_stock',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('items', 'current_stock',
               existing_type=sa.NUMERIC(precision=15, scale=3),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'current_stock',
               existing_type=sa.String(length=50),
               type_=sa.NUMERIC(precision=15, scale=3),
               existing_nullable=False)
    op.alter_column('items', 'opening_stock',
               existing_type=sa.String(length=50),
               type_=sa.NUMERIC(precision=15, scale=3),
               existing_nullable=False)
    op.create_index(op.f('ix_item_categories_type_id'), 'item_categories', ['type_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_endpoint'), 'activity_logs', ['endpoint'], unique=False)
    op.create_index(op.f('ix_activity_logs_activity_at'), 'activity_logs', ['activity_at'], unique=False)
    op.create_index(op.f('idx_activity_logs_user_id_activity_at'), 'activity_logs', ['user_id', 'activity_at'], unique=False)
    op.create_index(op.f('idx_activity_logs_status_activity_at'), 'activity_logs', ['activity_status', 'activity_at'], unique=False)
    op.create_index(op.f('idx_activity_logs_route_template_activity_at'), 'activity_logs', ['route_template', 'activity_at'], unique=False)
    op.create_index(op.f('idx_activity_logs_meta_gin'), 'activity_logs', ['meta'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
