"""add_donation_system

Revision ID: 3658d24ecdc7
Revises: 8bc4158ea414
Create Date: 2026-05-15 14:05:26.488696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3658d24ecdc7'
down_revision: Union[str, Sequence[str], None] = '8bc4158ea414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donation_date', sa.Date(), nullable=False),
    sa.Column('devotee_name', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donation_entries_donation_date'), 'donation_entries', ['donation_date'], unique=False)
    op.create_index(op.f('ix_donation_entries_status'), 'donation_entries', ['status'], unique=False)
    op.create_index(op.f('ix_donation_entries_user_id'), 'donation_entries', ['user_id'], unique=False)
    op.create_table('donation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donation_entry_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=False),
    sa.Column('unit_cost_at_time', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['donation_entry_id'], ['donation_entries.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donation_items_donation_entry_id'), 'donation_items', ['donation_entry_id'], unique=False)
    op.create_index(op.f('ix_donation_items_item_id'), 'donation_items', ['item_id'], unique=False)
    
    # Missing indexes from previous migrations (if any)
    # op.create_index(op.f('ix_purchase_return_entries_purchase_entry_id'), 'purchase_return_entries', ['purchase_entry_id'], unique=False)
    # op.create_index(op.f('ix_purchase_return_entries_return_date'), 'purchase_return_entries', ['return_date'], unique=False)
    # op.create_index(op.f('ix_purchase_return_entries_status'), 'purchase_return_entries', ['status'], unique=False)
    # op.create_index(op.f('ix_purchase_return_entries_user_id'), 'purchase_return_entries', ['user_id'], unique=False)
    # op.create_index(op.f('ix_purchase_return_entries_vendor_id'), 'purchase_return_entries', ['vendor_id'], unique=False)
    # op.create_index(op.f('ix_purchase_return_items_item_id'), 'purchase_return_items', ['item_id'], unique=False)
    # op.create_index(op.f('ix_purchase_return_items_return_entry_id'), 'purchase_return_items', ['return_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donation_items_item_id'), table_name='donation_items')
    op.drop_index(op.f('ix_donation_items_donation_entry_id'), table_name='donation_items')
    op.drop_table('donation_items')
    op.drop_index(op.f('ix_donation_entries_user_id'), table_name='donation_entries')
    op.drop_index(op.f('ix_donation_entries_status'), table_name='donation_entries')
    op.drop_index(op.f('ix_donation_entries_donation_date'), table_name='donation_entries')
    op.drop_table('donation_entries')
    # ### end Alembic commands ###
