"""add financial_year_id to token_generations

Revision ID: 6d4b27722dca
Revises: ab12cd34ef56
Create Date: 2026-05-07 14:38:50.995839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d4b27722dca'
down_revision: Union[str, Sequence[str], None] = 'ab12cd34ef56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().engine.dialect.has_table(op.get_bind(), 'notifications'):
        op.drop_table('notifications')
    op.add_column('token_generations', sa.Column('financial_year_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_token_generations_financial_year', 'token_generations', 'financial_years', ['financial_year_id'], ['id'])
    
    # Link existing records to the new financial year (ID=1)
    op.execute("UPDATE token_generations SET financial_year_id = 1")
    # Now make it NOT NULL if there are records, or just ensure it for future
    # op.alter_column('token_generations', 'financial_year_id', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token_generations', type_='foreignkey')
    op.drop_column('token_generations', 'financial_year_id')
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('notification_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('link', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    # ### end Alembic commands ###
