"""add_financial_year_system

Revision ID: 7d4293949424
Revises: f964efe7af59
Create Date: 2026-05-07 09:48:34.467027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d4293949424'
down_revision: Union[str, Sequence[str], None] = 'f964efe7af59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    
    # SEED DEFAULT FINANCIAL YEAR
    op.execute("INSERT INTO financial_years (name, start_date, end_date, is_active, status) VALUES ('2024-25', '2024-04-01', '2025-03-31', true, 1)")

    tables_to_update = [
        'chefs', 'consumption_entries', 'daily_stock_summary', 'item_categories',
        'item_types', 'items', 'menu_items', 'monthly_stock_summary',
        'purchase_entries', 'stock_adjustments', 'stock_ledger', 'units',
        'vendor_payments', 'vendors', 'wastage_entries'
    ]

    for table in tables_to_update:
        op.add_column(table, sa.Column('financial_year_id', sa.Integer(), nullable=True))
        op.create_foreign_key(f'fk_{table}_financial_year', table, 'financial_years', ['financial_year_id'], ['id'])
        # Link existing records to the new financial year (ID=1)
        op.execute(f"UPDATE {table} SET financial_year_id = 1")
        # Now make it NOT NULL
        op.alter_column(table, 'financial_year_id', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    tables_to_update = [
        'chefs', 'consumption_entries', 'daily_stock_summary', 'item_categories',
        'item_types', 'items', 'menu_items', 'monthly_stock_summary',
        'purchase_entries', 'stock_adjustments', 'stock_ledger', 'units',
        'vendor_payments', 'vendors', 'wastage_entries'
    ]

    for table in reversed(tables_to_update):
        op.drop_constraint(f'fk_{table}_financial_year', table, type_='foreignkey')
        op.drop_column(table, 'financial_year_id')

    op.drop_table('financial_years')
    # ### end Alembic commands ###
