"""add_indexes_to_all_tables

Revision ID: 8bc4158ea414
Revises: 2fcdeda76a9a
Create Date: 2026-05-14 00:50:12.889109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8bc4158ea414'
down_revision: Union[str, Sequence[str], None] = '2fcdeda76a9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_details_2027_12')
    op.drop_table('token_details_2026_10')
    op.drop_table('token_details_2027_01')
    op.drop_table('token_details_2027_02')
    op.drop_table('token_details_2027_06')
    op.drop_table('token_details_2026_08')
    op.drop_table('token_details_2026_11')
    op.drop_table('token_details_2026_02')
    op.drop_table('token_details_2026_06')
    op.drop_table('token_details_2027_11')
    op.drop_table('token_details_2026_05')
    op.drop_table('token_details_2027_05')
    op.drop_table('token_details_2026_03')
    op.drop_table('token_details_2027_09')
    op.drop_table('token_details_2026_04')
    op.drop_table('token_details_2026_01')
    op.drop_table('token_details_2027_08')
    op.drop_table('token_details_2026_07')
    op.drop_table('token_details_2026_09')
    op.drop_table('token_details_2027_04')
    op.drop_table('token_details_2027_03')
    op.drop_table('token_details_2027_10')
    op.drop_table('token_details_2026_12')
    op.drop_table('token_details_2027_07')
    op.create_index(op.f('ix_activity_logs_activity_at'), 'activity_logs', ['activity_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_endpoint'), 'activity_logs', ['endpoint'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_consumption_entries_status'), 'consumption_entries', ['status'], unique=False)
    op.create_index(op.f('ix_consumption_entries_usage_date'), 'consumption_entries', ['usage_date'], unique=False)
    op.create_index(op.f('ix_consumption_entries_user_id'), 'consumption_entries', ['user_id'], unique=False)
    op.create_index(op.f('ix_consumption_items_consumption_entry_id'), 'consumption_items', ['consumption_entry_id'], unique=False)
    op.create_index(op.f('ix_consumption_items_item_id'), 'consumption_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_consumption_items_usage_date'), 'consumption_items', ['usage_date'], unique=False)
    op.create_index(op.f('ix_daily_stock_summary_item_id'), 'daily_stock_summary', ['item_id'], unique=False)
    op.create_index(op.f('ix_daily_stock_summary_summary_date'), 'daily_stock_summary', ['summary_date'], unique=False)
    op.create_index(op.f('ix_item_categories_status'), 'item_categories', ['status'], unique=False)
    op.create_index(op.f('ix_item_categories_type_id'), 'item_categories', ['type_id'], unique=False)
    op.create_index(op.f('ix_item_prices_item_id'), 'item_prices', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_prices_purchase_entry_id'), 'item_prices', ['purchase_entry_id'], unique=False)
    op.create_index(op.f('ix_item_serial_numbers_item_id'), 'item_serial_numbers', ['item_id'], unique=False)
    op.create_index(op.f('ix_item_serial_numbers_status'), 'item_serial_numbers', ['status'], unique=False)
    op.create_index(op.f('ix_item_types_status'), 'item_types', ['status'], unique=False)
    op.create_index(op.f('ix_items_category_id'), 'items', ['category_id'], unique=False)
    op.create_index(op.f('ix_items_display_order'), 'items', ['display_order'], unique=False)
    op.create_index(op.f('ix_items_status'), 'items', ['status'], unique=False)
    op.create_index(op.f('ix_items_unit_id'), 'items', ['unit_id'], unique=False)
    op.create_index(op.f('ix_login_history_logged_in_at'), 'login_history', ['logged_in_at'], unique=False)
    op.create_index(op.f('ix_login_history_user_id'), 'login_history', ['user_id'], unique=False)
    op.create_index(op.f('ix_menu_items_status'), 'menu_items', ['status'], unique=False)
    op.create_index(op.f('ix_menu_items_unit_id'), 'menu_items', ['unit_id'], unique=False)
    op.create_index(op.f('ix_monthly_stock_summary_item_id'), 'monthly_stock_summary', ['item_id'], unique=False)
    op.create_index(op.f('ix_monthly_stock_summary_summary_month'), 'monthly_stock_summary', ['summary_month'], unique=False)
    op.create_index(op.f('ix_purchase_bills_purchase_id'), 'purchase_bills', ['purchase_id'], unique=False)
    op.create_index(op.f('ix_purchase_entries_purchase_date'), 'purchase_entries', ['purchase_date'], unique=False)
    op.create_index(op.f('ix_purchase_entries_status'), 'purchase_entries', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_entries_user_id'), 'purchase_entries', ['user_id'], unique=False)
    op.create_index(op.f('ix_purchase_entries_vendor_id'), 'purchase_entries', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_purchase_items_item_id'), 'purchase_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_purchase_items_purchase_date'), 'purchase_items', ['purchase_date'], unique=False)
    op.create_index(op.f('ix_purchase_items_purchase_entry_id'), 'purchase_items', ['purchase_entry_id'], unique=False)
    op.create_index(op.f('ix_purchase_items_status'), 'purchase_items', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_return_entries_purchase_entry_id'), 'purchase_return_entries', ['purchase_entry_id'], unique=False)
    op.create_index(op.f('ix_purchase_return_entries_return_date'), 'purchase_return_entries', ['return_date'], unique=False)
    op.create_index(op.f('ix_purchase_return_entries_status'), 'purchase_return_entries', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_return_entries_user_id'), 'purchase_return_entries', ['user_id'], unique=False)
    op.create_index(op.f('ix_purchase_return_entries_vendor_id'), 'purchase_return_entries', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_purchase_return_items_item_id'), 'purchase_return_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_purchase_return_items_return_entry_id'), 'purchase_return_items', ['return_entry_id'], unique=False)
    op.create_index(op.f('ix_role_privileges_privilege_id'), 'role_privileges', ['privilege_id'], unique=False)
    op.create_index(op.f('ix_role_privileges_role_id'), 'role_privileges', ['role_id'], unique=False)
    op.create_index(op.f('ix_stock_adjustments_adjustment_date'), 'stock_adjustments', ['adjustment_date'], unique=False)
    op.create_index(op.f('ix_stock_adjustments_consumption_entry_id'), 'stock_adjustments', ['consumption_entry_id'], unique=False)
    op.create_index(op.f('ix_stock_adjustments_item_id'), 'stock_adjustments', ['item_id'], unique=False)
    op.create_index(op.f('ix_stock_adjustments_user_id'), 'stock_adjustments', ['user_id'], unique=False)
    op.create_index(op.f('ix_stock_ledger_item_id'), 'stock_ledger', ['item_id'], unique=False)
    op.create_index(op.f('ix_stock_ledger_ref_id'), 'stock_ledger', ['ref_id'], unique=False)
    op.create_index(op.f('ix_stock_ledger_ref_table'), 'stock_ledger', ['ref_table'], unique=False)
    op.create_index(op.f('ix_stock_ledger_status'), 'stock_ledger', ['status'], unique=False)
    op.create_index(op.f('ix_stock_ledger_txn_date'), 'stock_ledger', ['txn_date'], unique=False)
    op.create_index(op.f('ix_stock_ledger_txn_type'), 'stock_ledger', ['txn_type'], unique=False)
    op.create_index(op.f('ix_token_details_generation_id'), 'token_details', ['generation_id'], unique=False)
    op.create_index(op.f('ix_units_status'), 'units', ['status'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_vendor_payments_payment_date'), 'vendor_payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_vendor_payments_status'), 'vendor_payments', ['status'], unique=False)
    op.create_index(op.f('ix_vendor_payments_user_id'), 'vendor_payments', ['user_id'], unique=False)
    op.create_index(op.f('ix_vendor_payments_vendor_id'), 'vendor_payments', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_vendors_status'), 'vendors', ['status'], unique=False)
    op.create_index(op.f('ix_wastage_entries_consumption_entry_id'), 'wastage_entries', ['consumption_entry_id'], unique=False)
    op.create_index(op.f('ix_wastage_entries_status'), 'wastage_entries', ['status'], unique=False)
    op.create_index(op.f('ix_wastage_entries_user_id'), 'wastage_entries', ['user_id'], unique=False)
    op.create_index(op.f('ix_wastage_entries_wastage_date'), 'wastage_entries', ['wastage_date'], unique=False)
    op.create_index(op.f('ix_wastage_items_consumption_entry_id'), 'wastage_items', ['consumption_entry_id'], unique=False)
    op.create_index(op.f('ix_wastage_items_item_id'), 'wastage_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_wastage_items_menu_item_id'), 'wastage_items', ['menu_item_id'], unique=False)
    op.create_index(op.f('ix_wastage_items_wastage_date'), 'wastage_items', ['wastage_date'], unique=False)
    op.create_index(op.f('ix_wastage_items_wastage_entry_id'), 'wastage_items', ['wastage_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wastage_items_wastage_entry_id'), table_name='wastage_items')
    op.drop_index(op.f('ix_wastage_items_wastage_date'), table_name='wastage_items')
    op.drop_index(op.f('ix_wastage_items_menu_item_id'), table_name='wastage_items')
    op.drop_index(op.f('ix_wastage_items_item_id'), table_name='wastage_items')
    op.drop_index(op.f('ix_wastage_items_consumption_entry_id'), table_name='wastage_items')
    op.drop_index(op.f('ix_wastage_entries_wastage_date'), table_name='wastage_entries')
    op.drop_index(op.f('ix_wastage_entries_user_id'), table_name='wastage_entries')
    op.drop_index(op.f('ix_wastage_entries_status'), table_name='wastage_entries')
    op.drop_index(op.f('ix_wastage_entries_consumption_entry_id'), table_name='wastage_entries')
    op.drop_index(op.f('ix_vendors_status'), table_name='vendors')
    op.drop_index(op.f('ix_vendor_payments_vendor_id'), table_name='vendor_payments')
    op.drop_index(op.f('ix_vendor_payments_user_id'), table_name='vendor_payments')
    op.drop_index(op.f('ix_vendor_payments_status'), table_name='vendor_payments')
    op.drop_index(op.f('ix_vendor_payments_payment_date'), table_name='vendor_payments')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_units_status'), table_name='units')
    op.drop_index(op.f('ix_token_details_generation_id'), table_name='token_details')
    op.drop_index(op.f('ix_stock_ledger_txn_type'), table_name='stock_ledger')
    op.drop_index(op.f('ix_stock_ledger_txn_date'), table_name='stock_ledger')
    op.drop_index(op.f('ix_stock_ledger_status'), table_name='stock_ledger')
    op.drop_index(op.f('ix_stock_ledger_ref_table'), table_name='stock_ledger')
    op.drop_index(op.f('ix_stock_ledger_ref_id'), table_name='stock_ledger')
    op.drop_index(op.f('ix_stock_ledger_item_id'), table_name='stock_ledger')
    op.drop_index(op.f('ix_stock_adjustments_user_id'), table_name='stock_adjustments')
    op.drop_index(op.f('ix_stock_adjustments_item_id'), table_name='stock_adjustments')
    op.drop_index(op.f('ix_stock_adjustments_consumption_entry_id'), table_name='stock_adjustments')
    op.drop_index(op.f('ix_stock_adjustments_adjustment_date'), table_name='stock_adjustments')
    op.drop_index(op.f('ix_role_privileges_role_id'), table_name='role_privileges')
    op.drop_index(op.f('ix_role_privileges_privilege_id'), table_name='role_privileges')
    op.drop_index(op.f('ix_purchase_return_items_return_entry_id'), table_name='purchase_return_items')
    op.drop_index(op.f('ix_purchase_return_items_item_id'), table_name='purchase_return_items')
    op.drop_index(op.f('ix_purchase_return_entries_vendor_id'), table_name='purchase_return_entries')
    op.drop_index(op.f('ix_purchase_return_entries_user_id'), table_name='purchase_return_entries')
    op.drop_index(op.f('ix_purchase_return_entries_status'), table_name='purchase_return_entries')
    op.drop_index(op.f('ix_purchase_return_entries_return_date'), table_name='purchase_return_entries')
    op.drop_index(op.f('ix_purchase_return_entries_purchase_entry_id'), table_name='purchase_return_entries')
    op.drop_index(op.f('ix_purchase_items_status'), table_name='purchase_items')
    op.drop_index(op.f('ix_purchase_items_purchase_entry_id'), table_name='purchase_items')
    op.drop_index(op.f('ix_purchase_items_purchase_date'), table_name='purchase_items')
    op.drop_index(op.f('ix_purchase_items_item_id'), table_name='purchase_items')
    op.drop_index(op.f('ix_purchase_entries_vendor_id'), table_name='purchase_entries')
    op.drop_index(op.f('ix_purchase_entries_user_id'), table_name='purchase_entries')
    op.drop_index(op.f('ix_purchase_entries_status'), table_name='purchase_entries')
    op.drop_index(op.f('ix_purchase_entries_purchase_date'), table_name='purchase_entries')
    op.drop_index(op.f('ix_purchase_bills_purchase_id'), table_name='purchase_bills')
    op.drop_index(op.f('ix_monthly_stock_summary_summary_month'), table_name='monthly_stock_summary')
    op.drop_index(op.f('ix_monthly_stock_summary_item_id'), table_name='monthly_stock_summary')
    op.drop_index(op.f('ix_menu_items_unit_id'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_status'), table_name='menu_items')
    op.drop_index(op.f('ix_login_history_user_id'), table_name='login_history')
    op.drop_index(op.f('ix_login_history_logged_in_at'), table_name='login_history')
    op.drop_index(op.f('ix_items_unit_id'), table_name='items')
    op.drop_index(op.f('ix_items_status'), table_name='items')
    op.drop_index(op.f('ix_items_display_order'), table_name='items')
    op.drop_index(op.f('ix_items_category_id'), table_name='items')
    op.drop_index(op.f('ix_item_types_status'), table_name='item_types')
    op.drop_index(op.f('ix_item_serial_numbers_status'), table_name='item_serial_numbers')
    op.drop_index(op.f('ix_item_serial_numbers_item_id'), table_name='item_serial_numbers')
    op.drop_index(op.f('ix_item_prices_purchase_entry_id'), table_name='item_prices')
    op.drop_index(op.f('ix_item_prices_item_id'), table_name='item_prices')
    op.drop_index(op.f('ix_item_categories_type_id'), table_name='item_categories')
    op.drop_index(op.f('ix_item_categories_status'), table_name='item_categories')
    op.drop_index(op.f('ix_daily_stock_summary_summary_date'), table_name='daily_stock_summary')
    op.drop_index(op.f('ix_daily_stock_summary_item_id'), table_name='daily_stock_summary')
    op.drop_index(op.f('ix_consumption_items_usage_date'), table_name='consumption_items')
    op.drop_index(op.f('ix_consumption_items_item_id'), table_name='consumption_items')
    op.drop_index(op.f('ix_consumption_items_consumption_entry_id'), table_name='consumption_items')
    op.drop_index(op.f('ix_consumption_entries_user_id'), table_name='consumption_entries')
    op.drop_index(op.f('ix_consumption_entries_usage_date'), table_name='consumption_entries')
    op.drop_index(op.f('ix_consumption_entries_status'), table_name='consumption_entries')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_endpoint'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_activity_at'), table_name='activity_logs')
    op.create_table('token_details_2027_07',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_07_pkey'))
    )
    op.create_table('token_details_2026_12',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_12_pkey'))
    )
    op.create_table('token_details_2027_10',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_10_pkey'))
    )
    op.create_table('token_details_2027_03',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_03_pkey'))
    )
    op.create_table('token_details_2027_04',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_04_pkey'))
    )
    op.create_table('token_details_2026_09',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_09_pkey'))
    )
    op.create_table('token_details_2026_07',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_07_pkey'))
    )
    op.create_table('token_details_2027_08',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_08_pkey'))
    )
    op.create_table('token_details_2026_01',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_01_pkey'))
    )
    op.create_table('token_details_2026_04',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_04_pkey'))
    )
    op.create_table('token_details_2027_09',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_09_pkey'))
    )
    op.create_table('token_details_2026_03',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_03_pkey'))
    )
    op.create_table('token_details_2027_05',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_05_pkey'))
    )
    op.create_table('token_details_2026_05',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_05_pkey'))
    )
    op.create_table('token_details_2027_11',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_11_pkey'))
    )
    op.create_table('token_details_2026_06',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_06_pkey'))
    )
    op.create_table('token_details_2026_02',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_02_pkey'))
    )
    op.create_table('token_details_2026_11',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_11_pkey'))
    )
    op.create_table('token_details_2026_08',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_08_pkey'))
    )
    op.create_table('token_details_2027_06',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_06_pkey'))
    )
    op.create_table('token_details_2027_02',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_02_pkey'))
    )
    op.create_table('token_details_2027_01',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_01_pkey'))
    )
    op.create_table('token_details_2026_10',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_10_pkey'))
    )
    op.create_table('token_details_2027_12',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_12_pkey'))
    )
    # ### end Alembic commands ###
