"""Add token_file_path

Revision ID: abf93fce7c2f
Revises: d5e6f7a8b9c0
Create Date: 2026-07-08 20:54:59.112783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abf93fce7c2f'
down_revision: Union[str, Sequence[str], None] = 'd5e6f7a8b9c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('token_details_2026_02_created_by_idx'), table_name='token_details_2026_02')
    op.drop_index(op.f('token_details_2026_02_financial_year_id_idx'), table_name='token_details_2026_02')
    op.drop_index(op.f('token_details_2026_02_generation_id_idx'), table_name='token_details_2026_02')
    op.drop_index(op.f('token_details_2026_02_receipt_display_number_idx'), table_name='token_details_2026_02')
    op.drop_index(op.f('token_details_2026_02_updated_by_idx'), table_name='token_details_2026_02')
    op.drop_table('token_details_2026_02')
    op.drop_index(op.f('token_details_2027_05_created_by_idx'), table_name='token_details_2027_05')
    op.drop_index(op.f('token_details_2027_05_financial_year_id_idx'), table_name='token_details_2027_05')
    op.drop_index(op.f('token_details_2027_05_generation_id_idx'), table_name='token_details_2027_05')
    op.drop_index(op.f('token_details_2027_05_receipt_display_number_idx'), table_name='token_details_2027_05')
    op.drop_index(op.f('token_details_2027_05_updated_by_idx'), table_name='token_details_2027_05')
    op.drop_table('token_details_2027_05')
    op.drop_index(op.f('token_details_2027_03_created_by_idx'), table_name='token_details_2027_03')
    op.drop_index(op.f('token_details_2027_03_financial_year_id_idx'), table_name='token_details_2027_03')
    op.drop_index(op.f('token_details_2027_03_generation_id_idx'), table_name='token_details_2027_03')
    op.drop_index(op.f('token_details_2027_03_receipt_display_number_idx'), table_name='token_details_2027_03')
    op.drop_index(op.f('token_details_2027_03_updated_by_idx'), table_name='token_details_2027_03')
    op.drop_table('token_details_2027_03')
    op.drop_index(op.f('token_details_2027_11_created_by_idx'), table_name='token_details_2027_11')
    op.drop_index(op.f('token_details_2027_11_financial_year_id_idx'), table_name='token_details_2027_11')
    op.drop_index(op.f('token_details_2027_11_generation_id_idx'), table_name='token_details_2027_11')
    op.drop_index(op.f('token_details_2027_11_receipt_display_number_idx'), table_name='token_details_2027_11')
    op.drop_index(op.f('token_details_2027_11_updated_by_idx'), table_name='token_details_2027_11')
    op.drop_table('token_details_2027_11')
    op.drop_index(op.f('token_details_2027_12_created_by_idx'), table_name='token_details_2027_12')
    op.drop_index(op.f('token_details_2027_12_financial_year_id_idx'), table_name='token_details_2027_12')
    op.drop_index(op.f('token_details_2027_12_generation_id_idx'), table_name='token_details_2027_12')
    op.drop_index(op.f('token_details_2027_12_receipt_display_number_idx'), table_name='token_details_2027_12')
    op.drop_index(op.f('token_details_2027_12_updated_by_idx'), table_name='token_details_2027_12')
    op.drop_table('token_details_2027_12')
    op.drop_index(op.f('token_details_2027_02_created_by_idx'), table_name='token_details_2027_02')
    op.drop_index(op.f('token_details_2027_02_financial_year_id_idx'), table_name='token_details_2027_02')
    op.drop_index(op.f('token_details_2027_02_generation_id_idx'), table_name='token_details_2027_02')
    op.drop_index(op.f('token_details_2027_02_receipt_display_number_idx'), table_name='token_details_2027_02')
    op.drop_index(op.f('token_details_2027_02_updated_by_idx'), table_name='token_details_2027_02')
    op.drop_table('token_details_2027_02')
    op.drop_index(op.f('token_details_2027_01_created_by_idx'), table_name='token_details_2027_01')
    op.drop_index(op.f('token_details_2027_01_financial_year_id_idx'), table_name='token_details_2027_01')
    op.drop_index(op.f('token_details_2027_01_generation_id_idx'), table_name='token_details_2027_01')
    op.drop_index(op.f('token_details_2027_01_receipt_display_number_idx'), table_name='token_details_2027_01')
    op.drop_index(op.f('token_details_2027_01_updated_by_idx'), table_name='token_details_2027_01')
    op.drop_table('token_details_2027_01')
    op.drop_index(op.f('token_details_2026_05_created_by_idx'), table_name='token_details_2026_05')
    op.drop_index(op.f('token_details_2026_05_financial_year_id_idx'), table_name='token_details_2026_05')
    op.drop_index(op.f('token_details_2026_05_generation_id_idx'), table_name='token_details_2026_05')
    op.drop_index(op.f('token_details_2026_05_receipt_display_number_idx'), table_name='token_details_2026_05')
    op.drop_index(op.f('token_details_2026_05_updated_by_idx'), table_name='token_details_2026_05')
    op.drop_table('token_details_2026_05')
    op.drop_index(op.f('token_details_2027_10_created_by_idx'), table_name='token_details_2027_10')
    op.drop_index(op.f('token_details_2027_10_financial_year_id_idx'), table_name='token_details_2027_10')
    op.drop_index(op.f('token_details_2027_10_generation_id_idx'), table_name='token_details_2027_10')
    op.drop_index(op.f('token_details_2027_10_receipt_display_number_idx'), table_name='token_details_2027_10')
    op.drop_index(op.f('token_details_2027_10_updated_by_idx'), table_name='token_details_2027_10')
    op.drop_table('token_details_2027_10')
    op.drop_index(op.f('token_details_2026_03_created_by_idx'), table_name='token_details_2026_03')
    op.drop_index(op.f('token_details_2026_03_financial_year_id_idx'), table_name='token_details_2026_03')
    op.drop_index(op.f('token_details_2026_03_generation_id_idx'), table_name='token_details_2026_03')
    op.drop_index(op.f('token_details_2026_03_receipt_display_number_idx'), table_name='token_details_2026_03')
    op.drop_index(op.f('token_details_2026_03_updated_by_idx'), table_name='token_details_2026_03')
    op.drop_table('token_details_2026_03')
    op.drop_index(op.f('token_details_2026_10_created_by_idx'), table_name='token_details_2026_10')
    op.drop_index(op.f('token_details_2026_10_financial_year_id_idx'), table_name='token_details_2026_10')
    op.drop_index(op.f('token_details_2026_10_generation_id_idx'), table_name='token_details_2026_10')
    op.drop_index(op.f('token_details_2026_10_receipt_display_number_idx'), table_name='token_details_2026_10')
    op.drop_index(op.f('token_details_2026_10_updated_by_idx'), table_name='token_details_2026_10')
    op.drop_table('token_details_2026_10')
    op.drop_index(op.f('token_details_2026_12_created_by_idx'), table_name='token_details_2026_12')
    op.drop_index(op.f('token_details_2026_12_financial_year_id_idx'), table_name='token_details_2026_12')
    op.drop_index(op.f('token_details_2026_12_generation_id_idx'), table_name='token_details_2026_12')
    op.drop_index(op.f('token_details_2026_12_receipt_display_number_idx'), table_name='token_details_2026_12')
    op.drop_index(op.f('token_details_2026_12_updated_by_idx'), table_name='token_details_2026_12')
    op.drop_table('token_details_2026_12')
    op.drop_index(op.f('token_details_2026_11_created_by_idx'), table_name='token_details_2026_11')
    op.drop_index(op.f('token_details_2026_11_financial_year_id_idx'), table_name='token_details_2026_11')
    op.drop_index(op.f('token_details_2026_11_generation_id_idx'), table_name='token_details_2026_11')
    op.drop_index(op.f('token_details_2026_11_receipt_display_number_idx'), table_name='token_details_2026_11')
    op.drop_index(op.f('token_details_2026_11_updated_by_idx'), table_name='token_details_2026_11')
    op.drop_table('token_details_2026_11')
    op.drop_index(op.f('token_details_2026_07_created_by_idx'), table_name='token_details_2026_07')
    op.drop_index(op.f('token_details_2026_07_financial_year_id_idx'), table_name='token_details_2026_07')
    op.drop_index(op.f('token_details_2026_07_generation_id_idx'), table_name='token_details_2026_07')
    op.drop_index(op.f('token_details_2026_07_receipt_display_number_idx'), table_name='token_details_2026_07')
    op.drop_index(op.f('token_details_2026_07_updated_by_idx'), table_name='token_details_2026_07')
    op.drop_table('token_details_2026_07')
    op.drop_index(op.f('token_details_2027_09_created_by_idx'), table_name='token_details_2027_09')
    op.drop_index(op.f('token_details_2027_09_financial_year_id_idx'), table_name='token_details_2027_09')
    op.drop_index(op.f('token_details_2027_09_generation_id_idx'), table_name='token_details_2027_09')
    op.drop_index(op.f('token_details_2027_09_receipt_display_number_idx'), table_name='token_details_2027_09')
    op.drop_index(op.f('token_details_2027_09_updated_by_idx'), table_name='token_details_2027_09')
    op.drop_table('token_details_2027_09')
    op.drop_index(op.f('token_details_2026_08_created_by_idx'), table_name='token_details_2026_08')
    op.drop_index(op.f('token_details_2026_08_financial_year_id_idx'), table_name='token_details_2026_08')
    op.drop_index(op.f('token_details_2026_08_generation_id_idx'), table_name='token_details_2026_08')
    op.drop_index(op.f('token_details_2026_08_receipt_display_number_idx'), table_name='token_details_2026_08')
    op.drop_index(op.f('token_details_2026_08_updated_by_idx'), table_name='token_details_2026_08')
    op.drop_table('token_details_2026_08')
    op.drop_index(op.f('token_details_2027_08_created_by_idx'), table_name='token_details_2027_08')
    op.drop_index(op.f('token_details_2027_08_financial_year_id_idx'), table_name='token_details_2027_08')
    op.drop_index(op.f('token_details_2027_08_generation_id_idx'), table_name='token_details_2027_08')
    op.drop_index(op.f('token_details_2027_08_receipt_display_number_idx'), table_name='token_details_2027_08')
    op.drop_index(op.f('token_details_2027_08_updated_by_idx'), table_name='token_details_2027_08')
    op.drop_table('token_details_2027_08')
    op.drop_index(op.f('token_details_2027_07_created_by_idx'), table_name='token_details_2027_07')
    op.drop_index(op.f('token_details_2027_07_financial_year_id_idx'), table_name='token_details_2027_07')
    op.drop_index(op.f('token_details_2027_07_generation_id_idx'), table_name='token_details_2027_07')
    op.drop_index(op.f('token_details_2027_07_receipt_display_number_idx'), table_name='token_details_2027_07')
    op.drop_index(op.f('token_details_2027_07_updated_by_idx'), table_name='token_details_2027_07')
    op.drop_table('token_details_2027_07')
    op.drop_index(op.f('token_details_2027_06_created_by_idx'), table_name='token_details_2027_06')
    op.drop_index(op.f('token_details_2027_06_financial_year_id_idx'), table_name='token_details_2027_06')
    op.drop_index(op.f('token_details_2027_06_generation_id_idx'), table_name='token_details_2027_06')
    op.drop_index(op.f('token_details_2027_06_receipt_display_number_idx'), table_name='token_details_2027_06')
    op.drop_index(op.f('token_details_2027_06_updated_by_idx'), table_name='token_details_2027_06')
    op.drop_table('token_details_2027_06')
    op.drop_index(op.f('token_details_2027_04_created_by_idx'), table_name='token_details_2027_04')
    op.drop_index(op.f('token_details_2027_04_financial_year_id_idx'), table_name='token_details_2027_04')
    op.drop_index(op.f('token_details_2027_04_generation_id_idx'), table_name='token_details_2027_04')
    op.drop_index(op.f('token_details_2027_04_receipt_display_number_idx'), table_name='token_details_2027_04')
    op.drop_index(op.f('token_details_2027_04_updated_by_idx'), table_name='token_details_2027_04')
    op.drop_table('token_details_2027_04')
    op.drop_index(op.f('token_details_2026_01_created_by_idx'), table_name='token_details_2026_01')
    op.drop_index(op.f('token_details_2026_01_financial_year_id_idx'), table_name='token_details_2026_01')
    op.drop_index(op.f('token_details_2026_01_generation_id_idx'), table_name='token_details_2026_01')
    op.drop_index(op.f('token_details_2026_01_receipt_display_number_idx'), table_name='token_details_2026_01')
    op.drop_index(op.f('token_details_2026_01_updated_by_idx'), table_name='token_details_2026_01')
    op.drop_table('token_details_2026_01')
    op.drop_index(op.f('token_details_2026_04_created_by_idx'), table_name='token_details_2026_04')
    op.drop_index(op.f('token_details_2026_04_financial_year_id_idx'), table_name='token_details_2026_04')
    op.drop_index(op.f('token_details_2026_04_generation_id_idx'), table_name='token_details_2026_04')
    op.drop_index(op.f('token_details_2026_04_receipt_display_number_idx'), table_name='token_details_2026_04')
    op.drop_index(op.f('token_details_2026_04_updated_by_idx'), table_name='token_details_2026_04')
    op.drop_table('token_details_2026_04')
    op.drop_index(op.f('token_details_2026_06_created_by_idx'), table_name='token_details_2026_06')
    op.drop_index(op.f('token_details_2026_06_financial_year_id_idx'), table_name='token_details_2026_06')
    op.drop_index(op.f('token_details_2026_06_generation_id_idx'), table_name='token_details_2026_06')
    op.drop_index(op.f('token_details_2026_06_receipt_display_number_idx'), table_name='token_details_2026_06')
    op.drop_index(op.f('token_details_2026_06_updated_by_idx'), table_name='token_details_2026_06')
    op.drop_table('token_details_2026_06')
    op.drop_index(op.f('token_details_2026_09_created_by_idx'), table_name='token_details_2026_09')
    op.drop_index(op.f('token_details_2026_09_financial_year_id_idx'), table_name='token_details_2026_09')
    op.drop_index(op.f('token_details_2026_09_generation_id_idx'), table_name='token_details_2026_09')
    op.drop_index(op.f('token_details_2026_09_receipt_display_number_idx'), table_name='token_details_2026_09')
    op.drop_index(op.f('token_details_2026_09_updated_by_idx'), table_name='token_details_2026_09')
    op.drop_table('token_details_2026_09')
    op.alter_column('donation_amount_masters', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('donation_types', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('item_categories', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('items', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('menu_items', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_unique_constraint('uq_receipt_sequence', 'receipt_sequences', ['financial_year_id', 'sequence_type', 'donation_type_id'])
    op.alter_column('roles', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.add_column('system_settings', sa.Column('token_file_path', sa.String(length=500), nullable=True))
    op.alter_column('units', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('vendors', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('users', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('units', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('system_settings', 'token_file_path')
    op.alter_column('roles', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_constraint('uq_receipt_sequence', 'receipt_sequences', type_='unique')
    op.alter_column('menu_items', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('items', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('item_categories', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('donation_types', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('donation_amount_masters', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.create_table('token_details_2026_09',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_prefix', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('receipt_display_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('fk_token_details_financial_year_id')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_09_pkey'))
    )
    op.create_index(op.f('token_details_2026_09_updated_by_idx'), 'token_details_2026_09', ['updated_by'], unique=False)
    op.create_index(op.f('token_details_2026_09_receipt_display_number_idx'), 'token_details_2026_09', ['receipt_display_number'], unique=False)
    op.create_index(op.f('token_details_2026_09_generation_id_idx'), 'token_details_2026_09', ['generation_id'], unique=False)
    op.create_index(op.f('token_details_2026_09_financial_year_id_idx'), 'token_details_2026_09', ['financial_year_id'], unique=False)
    op.create_index(op.f('token_details_2026_09_created_by_idx'), 'token_details_2026_09', ['created_by'], unique=False)
    op.create_table('token_details_2026_06',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_prefix', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('receipt_display_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('fk_token_details_financial_year_id')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_06_pkey'))
    )
    op.create_index(op.f('token_details_2026_06_updated_by_idx'), 'token_details_2026_06', ['updated_by'], unique=False)
    op.create_index(op.f('token_details_2026_06_receipt_display_number_idx'), 'token_details_2026_06', ['receipt_display_number'], unique=False)
    op.create_index(op.f('token_details_2026_06_generation_id_idx'), 'token_details_2026_06', ['generation_id'], unique=False)
    op.create_index(op.f('token_details_2026_06_financial_year_id_idx'), 'token_details_2026_06', ['financial_year_id'], unique=False)
    op.create_index(op.f('token_details_2026_06_created_by_idx'), 'token_details_2026_06', ['created_by'], unique=False)
    op.create_table('token_details_2026_04',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_prefix', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('receipt_display_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('fk_token_details_financial_year_id')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_04_pkey'))
    )
    op.create_index(op.f('token_details_2026_04_updated_by_idx'), 'token_details_2026_04', ['updated_by'], unique=False)
    op.create_index(op.f('token_details_2026_04_receipt_display_number_idx'), 'token_details_2026_04', ['receipt_display_number'], unique=False)
    op.create_index(op.f('token_details_2026_04_generation_id_idx'), 'token_details_2026_04', ['generation_id'], unique=False)
    op.create_index(op.f('token_details_2026_04_financial_year_id_idx'), 'token_details_2026_04', ['financial_year_id'], unique=False)
    op.create_index(op.f('token_details_2026_04_created_by_idx'), 'token_details_2026_04', ['created_by'], unique=False)
    op.create_table('token_details_2026_01',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_prefix', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('receipt_display_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('fk_token_details_financial_year_id')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_01_pkey'))
    )
    op.create_index(op.f('token_details_2026_01_updated_by_idx'), 'token_details_2026_01', ['updated_by'], unique=False)
    op.create_index(op.f('token_details_2026_01_receipt_display_number_idx'), 'token_details_2026_01', ['receipt_display_number'], unique=False)
    op.create_index(op.f('token_details_2026_01_generation_id_idx'), 'token_details_2026_01', ['generation_id'], unique=False)
    op.create_index(op.f('token_details_2026_01_financial_year_id_idx'), 'token_details_2026_01', ['financial_year_id'], unique=False)
    op.create_index(op.f('token_details_2026_01_created_by_idx'), 'token_details_2026_01', ['created_by'], unique=False)
    op.create_table('token_details_2027_04',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_prefix', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('receipt_display_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('fk_token_details_financial_year_id')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_04_pkey'))
    )
    op.create_index(op.f('token_details_2027_04_updated_by_idx'), 'token_details_2027_04', ['updated_by'], unique=False)
    op.create_index(op.f('token_details_2027_04_receipt_display_number_idx'), 'token_details_2027_04', ['receipt_display_number'], unique=False)
    op.create_index(op.f('token_details_2027_04_generation_id_idx'), 'token_details_2027_04', ['generation_id'], unique=False)
    op.create_index(op.f('token_details_2027_04_financial_year_id_idx'), 'token_details_2027_04', ['financial_year_id'], unique=False)
    op.create_index(op.f('token_details_2027_04_created_by_idx'), 'token_details_2027_04', ['created_by'], unique=False)
    op.create_table('token_details_2027_06',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_prefix', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('receipt_display_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('fk_token_details_financial_year_id')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_06_pkey'))
    )
    op.create_index(op.f('token_details_2027_06_updated_by_idx'), 'token_details_2027_06', ['updated_by'], unique=False)
    op.create_index(op.f('token_details_2027_06_receipt_display_number_idx'), 'token_details_2027_06', ['receipt_display_number'], unique=False)
    op.create_index(op.f('token_details_2027_06_generation_id_idx'), 'token_details_2027_06', ['generation_id'], unique=False)
    op.create_index(op.f('token_details_2027_06_financial_year_id_idx'), 'token_details_2027_06', ['financial_year_id'], unique=False)
    op.create_index(op.f('token_details_2027_06_created_by_idx'), 'token_details_2027_06', ['created_by'], unique=False)
    op.create_table('token_details_2027_07',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_prefix', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('receipt_display_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('fk_token_details_financial_year_id')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_07_pkey'))
    )
    op.create_index(op.f('token_details_2027_07_updated_by_idx'), 'token_details_2027_07', ['updated_by'], unique=False)
    op.create_index(op.f('token_details_2027_07_receipt_display_number_idx'), 'token_details_2027_07', ['receipt_display_number'], unique=False)
    op.create_index(op.f('token_details_2027_07_generation_id_idx'), 'token_details_2027_07', ['generation_id'], unique=False)
    op.create_index(op.f('token_details_2027_07_financial_year_id_idx'), 'token_details_2027_07', ['financial_year_id'], unique=False)
    op.create_index(op.f('token_details_2027_07_created_by_idx'), 'token_details_2027_07', ['created_by'], unique=False)
    op.create_table('token_details_2027_08',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_prefix', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('receipt_display_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('fk_token_details_financial_year_id')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_08_pkey'))
    )
    op.create_index(op.f('token_details_2027_08_updated_by_idx'), 'token_details_2027_08', ['updated_by'], unique=False)
    op.create_index(op.f('token_details_2027_08_receipt_display_number_idx'), 'token_details_2027_08', ['receipt_display_number'], unique=False)
    op.create_index(op.f('token_details_2027_08_generation_id_idx'), 'token_details_2027_08', ['generation_id'], unique=False)
    op.create_index(op.f('token_details_2027_08_financial_year_id_idx'), 'token_details_2027_08', ['financial_year_id'], unique=False)
    op.create_index(op.f('token_details_2027_08_created_by_idx'), 'token_details_2027_08', ['created_by'], unique=False)
    op.create_table('token_details_2026_08',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_prefix', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('receipt_display_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('fk_token_details_financial_year_id')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_08_pkey'))
    )
    op.create_index(op.f('token_details_2026_08_updated_by_idx'), 'token_details_2026_08', ['updated_by'], unique=False)
    op.create_index(op.f('token_details_2026_08_receipt_display_number_idx'), 'token_details_2026_08', ['receipt_display_number'], unique=False)
    op.create_index(op.f('token_details_2026_08_generation_id_idx'), 'token_details_2026_08', ['generation_id'], unique=False)
    op.create_index(op.f('token_details_2026_08_financial_year_id_idx'), 'token_details_2026_08', ['financial_year_id'], unique=False)
    op.create_index(op.f('token_details_2026_08_created_by_idx'), 'token_details_2026_08', ['created_by'], unique=False)
    op.create_table('token_details_2027_09',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_prefix', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('receipt_display_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('fk_token_details_financial_year_id')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_09_pkey'))
    )
    op.create_index(op.f('token_details_2027_09_updated_by_idx'), 'token_details_2027_09', ['updated_by'], unique=False)
    op.create_index(op.f('token_details_2027_09_receipt_display_number_idx'), 'token_details_2027_09', ['receipt_display_number'], unique=False)
    op.create_index(op.f('token_details_2027_09_generation_id_idx'), 'token_details_2027_09', ['generation_id'], unique=False)
    op.create_index(op.f('token_details_2027_09_financial_year_id_idx'), 'token_details_2027_09', ['financial_year_id'], unique=False)
    op.create_index(op.f('token_details_2027_09_created_by_idx'), 'token_details_2027_09', ['created_by'], unique=False)
    op.create_table('token_details_2026_07',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_prefix', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('receipt_display_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('fk_token_details_financial_year_id')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_07_pkey'))
    )
    op.create_index(op.f('token_details_2026_07_updated_by_idx'), 'token_details_2026_07', ['updated_by'], unique=False)
    op.create_index(op.f('token_details_2026_07_receipt_display_number_idx'), 'token_details_2026_07', ['receipt_display_number'], unique=False)
    op.create_index(op.f('token_details_2026_07_generation_id_idx'), 'token_details_2026_07', ['generation_id'], unique=False)
    op.create_index(op.f('token_details_2026_07_financial_year_id_idx'), 'token_details_2026_07', ['financial_year_id'], unique=False)
    op.create_index(op.f('token_details_2026_07_created_by_idx'), 'token_details_2026_07', ['created_by'], unique=False)
    op.create_table('token_details_2026_11',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_prefix', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('receipt_display_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('fk_token_details_financial_year_id')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_11_pkey'))
    )
    op.create_index(op.f('token_details_2026_11_updated_by_idx'), 'token_details_2026_11', ['updated_by'], unique=False)
    op.create_index(op.f('token_details_2026_11_receipt_display_number_idx'), 'token_details_2026_11', ['receipt_display_number'], unique=False)
    op.create_index(op.f('token_details_2026_11_generation_id_idx'), 'token_details_2026_11', ['generation_id'], unique=False)
    op.create_index(op.f('token_details_2026_11_financial_year_id_idx'), 'token_details_2026_11', ['financial_year_id'], unique=False)
    op.create_index(op.f('token_details_2026_11_created_by_idx'), 'token_details_2026_11', ['created_by'], unique=False)
    op.create_table('token_details_2026_12',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_prefix', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('receipt_display_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('fk_token_details_financial_year_id')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_12_pkey'))
    )
    op.create_index(op.f('token_details_2026_12_updated_by_idx'), 'token_details_2026_12', ['updated_by'], unique=False)
    op.create_index(op.f('token_details_2026_12_receipt_display_number_idx'), 'token_details_2026_12', ['receipt_display_number'], unique=False)
    op.create_index(op.f('token_details_2026_12_generation_id_idx'), 'token_details_2026_12', ['generation_id'], unique=False)
    op.create_index(op.f('token_details_2026_12_financial_year_id_idx'), 'token_details_2026_12', ['financial_year_id'], unique=False)
    op.create_index(op.f('token_details_2026_12_created_by_idx'), 'token_details_2026_12', ['created_by'], unique=False)
    op.create_table('token_details_2026_10',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_prefix', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('receipt_display_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('fk_token_details_financial_year_id')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_10_pkey'))
    )
    op.create_index(op.f('token_details_2026_10_updated_by_idx'), 'token_details_2026_10', ['updated_by'], unique=False)
    op.create_index(op.f('token_details_2026_10_receipt_display_number_idx'), 'token_details_2026_10', ['receipt_display_number'], unique=False)
    op.create_index(op.f('token_details_2026_10_generation_id_idx'), 'token_details_2026_10', ['generation_id'], unique=False)
    op.create_index(op.f('token_details_2026_10_financial_year_id_idx'), 'token_details_2026_10', ['financial_year_id'], unique=False)
    op.create_index(op.f('token_details_2026_10_created_by_idx'), 'token_details_2026_10', ['created_by'], unique=False)
    op.create_table('token_details_2026_03',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_prefix', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('receipt_display_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('fk_token_details_financial_year_id')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_03_pkey'))
    )
    op.create_index(op.f('token_details_2026_03_updated_by_idx'), 'token_details_2026_03', ['updated_by'], unique=False)
    op.create_index(op.f('token_details_2026_03_receipt_display_number_idx'), 'token_details_2026_03', ['receipt_display_number'], unique=False)
    op.create_index(op.f('token_details_2026_03_generation_id_idx'), 'token_details_2026_03', ['generation_id'], unique=False)
    op.create_index(op.f('token_details_2026_03_financial_year_id_idx'), 'token_details_2026_03', ['financial_year_id'], unique=False)
    op.create_index(op.f('token_details_2026_03_created_by_idx'), 'token_details_2026_03', ['created_by'], unique=False)
    op.create_table('token_details_2027_10',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_prefix', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('receipt_display_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('fk_token_details_financial_year_id')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_10_pkey'))
    )
    op.create_index(op.f('token_details_2027_10_updated_by_idx'), 'token_details_2027_10', ['updated_by'], unique=False)
    op.create_index(op.f('token_details_2027_10_receipt_display_number_idx'), 'token_details_2027_10', ['receipt_display_number'], unique=False)
    op.create_index(op.f('token_details_2027_10_generation_id_idx'), 'token_details_2027_10', ['generation_id'], unique=False)
    op.create_index(op.f('token_details_2027_10_financial_year_id_idx'), 'token_details_2027_10', ['financial_year_id'], unique=False)
    op.create_index(op.f('token_details_2027_10_created_by_idx'), 'token_details_2027_10', ['created_by'], unique=False)
    op.create_table('token_details_2026_05',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_prefix', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('receipt_display_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('fk_token_details_financial_year_id')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_05_pkey'))
    )
    op.create_index(op.f('token_details_2026_05_updated_by_idx'), 'token_details_2026_05', ['updated_by'], unique=False)
    op.create_index(op.f('token_details_2026_05_receipt_display_number_idx'), 'token_details_2026_05', ['receipt_display_number'], unique=False)
    op.create_index(op.f('token_details_2026_05_generation_id_idx'), 'token_details_2026_05', ['generation_id'], unique=False)
    op.create_index(op.f('token_details_2026_05_financial_year_id_idx'), 'token_details_2026_05', ['financial_year_id'], unique=False)
    op.create_index(op.f('token_details_2026_05_created_by_idx'), 'token_details_2026_05', ['created_by'], unique=False)
    op.create_table('token_details_2027_01',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_prefix', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('receipt_display_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('fk_token_details_financial_year_id')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_01_pkey'))
    )
    op.create_index(op.f('token_details_2027_01_updated_by_idx'), 'token_details_2027_01', ['updated_by'], unique=False)
    op.create_index(op.f('token_details_2027_01_receipt_display_number_idx'), 'token_details_2027_01', ['receipt_display_number'], unique=False)
    op.create_index(op.f('token_details_2027_01_generation_id_idx'), 'token_details_2027_01', ['generation_id'], unique=False)
    op.create_index(op.f('token_details_2027_01_financial_year_id_idx'), 'token_details_2027_01', ['financial_year_id'], unique=False)
    op.create_index(op.f('token_details_2027_01_created_by_idx'), 'token_details_2027_01', ['created_by'], unique=False)
    op.create_table('token_details_2027_02',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_prefix', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('receipt_display_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('fk_token_details_financial_year_id')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_02_pkey'))
    )
    op.create_index(op.f('token_details_2027_02_updated_by_idx'), 'token_details_2027_02', ['updated_by'], unique=False)
    op.create_index(op.f('token_details_2027_02_receipt_display_number_idx'), 'token_details_2027_02', ['receipt_display_number'], unique=False)
    op.create_index(op.f('token_details_2027_02_generation_id_idx'), 'token_details_2027_02', ['generation_id'], unique=False)
    op.create_index(op.f('token_details_2027_02_financial_year_id_idx'), 'token_details_2027_02', ['financial_year_id'], unique=False)
    op.create_index(op.f('token_details_2027_02_created_by_idx'), 'token_details_2027_02', ['created_by'], unique=False)
    op.create_table('token_details_2027_12',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_prefix', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('receipt_display_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('fk_token_details_financial_year_id')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_12_pkey'))
    )
    op.create_index(op.f('token_details_2027_12_updated_by_idx'), 'token_details_2027_12', ['updated_by'], unique=False)
    op.create_index(op.f('token_details_2027_12_receipt_display_number_idx'), 'token_details_2027_12', ['receipt_display_number'], unique=False)
    op.create_index(op.f('token_details_2027_12_generation_id_idx'), 'token_details_2027_12', ['generation_id'], unique=False)
    op.create_index(op.f('token_details_2027_12_financial_year_id_idx'), 'token_details_2027_12', ['financial_year_id'], unique=False)
    op.create_index(op.f('token_details_2027_12_created_by_idx'), 'token_details_2027_12', ['created_by'], unique=False)
    op.create_table('token_details_2027_11',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_prefix', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('receipt_display_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('fk_token_details_financial_year_id')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_11_pkey'))
    )
    op.create_index(op.f('token_details_2027_11_updated_by_idx'), 'token_details_2027_11', ['updated_by'], unique=False)
    op.create_index(op.f('token_details_2027_11_receipt_display_number_idx'), 'token_details_2027_11', ['receipt_display_number'], unique=False)
    op.create_index(op.f('token_details_2027_11_generation_id_idx'), 'token_details_2027_11', ['generation_id'], unique=False)
    op.create_index(op.f('token_details_2027_11_financial_year_id_idx'), 'token_details_2027_11', ['financial_year_id'], unique=False)
    op.create_index(op.f('token_details_2027_11_created_by_idx'), 'token_details_2027_11', ['created_by'], unique=False)
    op.create_table('token_details_2027_03',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_prefix', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('receipt_display_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('fk_token_details_financial_year_id')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_03_pkey'))
    )
    op.create_index(op.f('token_details_2027_03_updated_by_idx'), 'token_details_2027_03', ['updated_by'], unique=False)
    op.create_index(op.f('token_details_2027_03_receipt_display_number_idx'), 'token_details_2027_03', ['receipt_display_number'], unique=False)
    op.create_index(op.f('token_details_2027_03_generation_id_idx'), 'token_details_2027_03', ['generation_id'], unique=False)
    op.create_index(op.f('token_details_2027_03_financial_year_id_idx'), 'token_details_2027_03', ['financial_year_id'], unique=False)
    op.create_index(op.f('token_details_2027_03_created_by_idx'), 'token_details_2027_03', ['created_by'], unique=False)
    op.create_table('token_details_2027_05',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_prefix', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('receipt_display_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('fk_token_details_financial_year_id')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_05_pkey'))
    )
    op.create_index(op.f('token_details_2027_05_updated_by_idx'), 'token_details_2027_05', ['updated_by'], unique=False)
    op.create_index(op.f('token_details_2027_05_receipt_display_number_idx'), 'token_details_2027_05', ['receipt_display_number'], unique=False)
    op.create_index(op.f('token_details_2027_05_generation_id_idx'), 'token_details_2027_05', ['generation_id'], unique=False)
    op.create_index(op.f('token_details_2027_05_financial_year_id_idx'), 'token_details_2027_05', ['financial_year_id'], unique=False)
    op.create_index(op.f('token_details_2027_05_created_by_idx'), 'token_details_2027_05', ['created_by'], unique=False)
    op.create_table('token_details_2026_02',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_prefix', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('receipt_display_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('fk_token_details_financial_year_id')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_02_pkey'))
    )
    op.create_index(op.f('token_details_2026_02_updated_by_idx'), 'token_details_2026_02', ['updated_by'], unique=False)
    op.create_index(op.f('token_details_2026_02_receipt_display_number_idx'), 'token_details_2026_02', ['receipt_display_number'], unique=False)
    op.create_index(op.f('token_details_2026_02_generation_id_idx'), 'token_details_2026_02', ['generation_id'], unique=False)
    op.create_index(op.f('token_details_2026_02_financial_year_id_idx'), 'token_details_2026_02', ['financial_year_id'], unique=False)
    op.create_index(op.f('token_details_2026_02_created_by_idx'), 'token_details_2026_02', ['created_by'], unique=False)
    # ### end Alembic commands ###
