"""remove_chef_system

Revision ID: b3849b8badd6
Revises: 7d4293949424
Create Date: 2026-05-07 11:48:28.201825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3849b8badd6'
down_revision: Union[str, Sequence[str], None] = '7d4293949424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_details_2026_05')
    op.alter_column('consumption_entries', 'financial_year_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('consumption_entries_chef_id_fkey'), 'consumption_entries', type_='foreignkey')
    op.drop_column('consumption_entries', 'chef_id')
    op.drop_table('chefs')
    op.alter_column('daily_stock_summary', 'financial_year_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('item_categories', 'financial_year_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('item_types', 'financial_year_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('items', 'financial_year_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('menu_items', 'financial_year_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('monthly_stock_summary', 'financial_year_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('purchase_entries', 'financial_year_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('purchase_entries', 'cgst')
    op.drop_column('purchase_entries', 'sgst')
    op.drop_column('purchase_entries', 'igst')
    op.alter_column('stock_adjustments', 'financial_year_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stock_ledger', 'financial_year_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('units', 'financial_year_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vendor_payments', 'financial_year_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vendors', 'financial_year_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('vendors', 'gst_number')
    op.alter_column('wastage_entries', 'financial_year_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wastage_entries', 'financial_year_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('vendors', sa.Column('gst_number', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.alter_column('vendors', 'financial_year_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vendor_payments', 'financial_year_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('units', 'financial_year_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stock_ledger', 'financial_year_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stock_adjustments', 'financial_year_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('purchase_entries', sa.Column('igst', sa.NUMERIC(precision=15, scale=3), autoincrement=False, nullable=False))
    op.add_column('purchase_entries', sa.Column('sgst', sa.NUMERIC(precision=15, scale=3), autoincrement=False, nullable=False))
    op.add_column('purchase_entries', sa.Column('cgst', sa.NUMERIC(precision=15, scale=3), autoincrement=False, nullable=False))
    op.alter_column('purchase_entries', 'financial_year_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('monthly_stock_summary', 'financial_year_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('menu_items', 'financial_year_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('items', 'financial_year_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('item_types', 'financial_year_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('item_categories', 'financial_year_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_stock_summary', 'financial_year_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('consumption_entries', sa.Column('chef_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('consumption_entries_chef_id_fkey'), 'consumption_entries', 'chefs', ['chef_id'], ['id'])
    op.alter_column('consumption_entries', 'financial_year_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('token_details_2026_05',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_05_pkey'))
    )
    op.create_table('chefs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chef_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('chefs_created_by_fkey')),
    sa.ForeignKeyConstraint(['financial_year_id'], ['financial_years.id'], name=op.f('fk_chefs_financial_year')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('chefs_updated_by_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('chefs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chefs_pkey'))
    )
    # ### end Alembic commands ###
