"""remove_all_financial_year_fields

Revision ID: b3f88a449380
Revises: f003426e0e04
Create Date: 2026-05-08 22:25:32.598750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3f88a449380'
down_revision: Union[str, Sequence[str], None] = 'f003426e0e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('consumption_entries_financial_year_id_fkey'), 'consumption_entries', type_='foreignkey')
    op.drop_column('consumption_entries', 'financial_year_id')
    op.drop_constraint(op.f('daily_stock_summary_financial_year_id_fkey'), 'daily_stock_summary', type_='foreignkey')
    op.drop_column('daily_stock_summary', 'financial_year_id')
    op.drop_constraint(op.f('item_categories_financial_year_id_fkey'), 'item_categories', type_='foreignkey')
    op.drop_column('item_categories', 'financial_year_id')
    op.drop_constraint(op.f('item_types_financial_year_id_fkey'), 'item_types', type_='foreignkey')
    op.drop_column('item_types', 'financial_year_id')
    op.drop_constraint(op.f('items_financial_year_id_fkey'), 'items', type_='foreignkey')
    op.drop_column('items', 'financial_year_id')
    op.drop_constraint(op.f('menu_items_financial_year_id_fkey'), 'menu_items', type_='foreignkey')
    op.drop_column('menu_items', 'financial_year_id')
    op.drop_constraint(op.f('monthly_stock_summary_financial_year_id_fkey'), 'monthly_stock_summary', type_='foreignkey')
    op.drop_column('monthly_stock_summary', 'financial_year_id')
    op.drop_constraint(op.f('purchase_entries_financial_year_id_fkey'), 'purchase_entries', type_='foreignkey')
    op.drop_column('purchase_entries', 'financial_year_id')
    op.drop_constraint(op.f('role_privileges_updated_by_fkey'), 'role_privileges', type_='foreignkey')
    op.drop_constraint(op.f('role_privileges_created_by_fkey'), 'role_privileges', type_='foreignkey')
    op.drop_constraint(op.f('stock_adjustments_financial_year_id_fkey'), 'stock_adjustments', type_='foreignkey')
    op.drop_column('stock_adjustments', 'financial_year_id')
    op.drop_constraint(op.f('stock_ledger_financial_year_id_fkey'), 'stock_ledger', type_='foreignkey')
    op.drop_column('stock_ledger', 'financial_year_id')
    op.drop_constraint(op.f('token_generations_financial_year_id_fkey'), 'token_generations', type_='foreignkey')
    op.drop_column('token_generations', 'financial_year_id')
    op.drop_constraint(op.f('units_financial_year_id_fkey'), 'units', type_='foreignkey')
    op.drop_column('units', 'financial_year_id')
    op.drop_constraint(op.f('vendor_payments_financial_year_id_fkey'), 'vendor_payments', type_='foreignkey')
    op.drop_column('vendor_payments', 'financial_year_id')
    op.drop_constraint(op.f('vendors_financial_year_id_fkey'), 'vendors', type_='foreignkey')
    op.drop_column('vendors', 'financial_year_id')
    op.drop_constraint(op.f('wastage_entries_financial_year_id_fkey'), 'wastage_entries', type_='foreignkey')
    op.drop_column('wastage_entries', 'financial_year_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wastage_entries', sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('wastage_entries_financial_year_id_fkey'), 'wastage_entries', 'financial_years', ['financial_year_id'], ['id'])
    op.add_column('vendors', sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('vendors_financial_year_id_fkey'), 'vendors', 'financial_years', ['financial_year_id'], ['id'])
    op.add_column('vendor_payments', sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('vendor_payments_financial_year_id_fkey'), 'vendor_payments', 'financial_years', ['financial_year_id'], ['id'])
    op.add_column('units', sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('units_financial_year_id_fkey'), 'units', 'financial_years', ['financial_year_id'], ['id'])
    op.add_column('token_generations', sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('token_generations_financial_year_id_fkey'), 'token_generations', 'financial_years', ['financial_year_id'], ['id'])
    op.add_column('stock_ledger', sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('stock_ledger_financial_year_id_fkey'), 'stock_ledger', 'financial_years', ['financial_year_id'], ['id'])
    op.add_column('stock_adjustments', sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('stock_adjustments_financial_year_id_fkey'), 'stock_adjustments', 'financial_years', ['financial_year_id'], ['id'])
    op.create_foreign_key(op.f('role_privileges_created_by_fkey'), 'role_privileges', 'users', ['created_by'], ['id'])
    op.create_foreign_key(op.f('role_privileges_updated_by_fkey'), 'role_privileges', 'users', ['updated_by'], ['id'])
    op.add_column('purchase_entries', sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('purchase_entries_financial_year_id_fkey'), 'purchase_entries', 'financial_years', ['financial_year_id'], ['id'])
    op.add_column('monthly_stock_summary', sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('monthly_stock_summary_financial_year_id_fkey'), 'monthly_stock_summary', 'financial_years', ['financial_year_id'], ['id'])
    op.add_column('menu_items', sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('menu_items_financial_year_id_fkey'), 'menu_items', 'financial_years', ['financial_year_id'], ['id'])
    op.add_column('items', sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('items_financial_year_id_fkey'), 'items', 'financial_years', ['financial_year_id'], ['id'])
    op.add_column('item_types', sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('item_types_financial_year_id_fkey'), 'item_types', 'financial_years', ['financial_year_id'], ['id'])
    op.add_column('item_categories', sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('item_categories_financial_year_id_fkey'), 'item_categories', 'financial_years', ['financial_year_id'], ['id'])
    op.add_column('daily_stock_summary', sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('daily_stock_summary_financial_year_id_fkey'), 'daily_stock_summary', 'financial_years', ['financial_year_id'], ['id'])
    op.add_column('consumption_entries', sa.Column('financial_year_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('consumption_entries_financial_year_id_fkey'), 'consumption_entries', 'financial_years', ['financial_year_id'], ['id'])
    # ### end Alembic commands ###
