"""remove_wastage_reason

Revision ID: d12661aeccff
Revises: d437189dea9d
Create Date: 2026-05-10 00:44:35.792697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd12661aeccff'
down_revision: Union[str, Sequence[str], None] = 'd437189dea9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_details_2026_01')
    op.drop_table('token_details_2026_02')
    op.drop_table('token_details_2027_01')
    op.drop_table('token_details_2027_02')
    op.drop_table('token_details_2027_09')
    op.drop_table('token_details_2026_06')
    op.drop_table('token_details_2027_06')
    op.drop_table('token_details_2026_08')
    op.drop_table('token_details_2026_09')
    op.drop_table('token_details_2027_08')
    op.drop_table('token_details_2026_04')
    op.drop_table('token_details_2026_05')
    op.drop_table('token_details_2026_07')
    op.drop_table('token_details_2026_03')
    op.drop_table('token_details_2027_10')
    op.drop_table('token_details_2027_12')
    op.drop_table('token_details_2027_03')
    op.drop_table('token_details_2026_12')
    op.drop_table('token_details_2027_11')
    op.drop_table('token_details_2027_05')
    op.drop_table('token_details_2026_10')
    op.drop_table('token_details_2026_11')
    op.drop_table('token_details_2027_04')
    op.drop_table('token_details_2027_07')
    op.drop_column('wastage_entries', 'reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wastage_entries', sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_table('token_details_2027_07',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_07_pkey'))
    )
    op.create_table('token_details_2027_04',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_04_pkey'))
    )
    op.create_table('token_details_2026_11',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_11_pkey'))
    )
    op.create_table('token_details_2026_10',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_10_pkey'))
    )
    op.create_table('token_details_2027_05',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_05_pkey'))
    )
    op.create_table('token_details_2027_11',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_11_pkey'))
    )
    op.create_table('token_details_2026_12',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_12_pkey'))
    )
    op.create_table('token_details_2027_03',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_03_pkey'))
    )
    op.create_table('token_details_2027_12',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_12_pkey'))
    )
    op.create_table('token_details_2027_10',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_10_pkey'))
    )
    op.create_table('token_details_2026_03',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_03_pkey'))
    )
    op.create_table('token_details_2026_07',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_07_pkey'))
    )
    op.create_table('token_details_2026_05',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_05_pkey'))
    )
    op.create_table('token_details_2026_04',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_04_pkey'))
    )
    op.create_table('token_details_2027_08',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_08_pkey'))
    )
    op.create_table('token_details_2026_09',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_09_pkey'))
    )
    op.create_table('token_details_2026_08',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_08_pkey'))
    )
    op.create_table('token_details_2027_06',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_06_pkey'))
    )
    op.create_table('token_details_2026_06',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_06_pkey'))
    )
    op.create_table('token_details_2027_09',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_09_pkey'))
    )
    op.create_table('token_details_2027_02',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_02_pkey'))
    )
    op.create_table('token_details_2027_01',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2027_01_pkey'))
    )
    op.create_table('token_details_2026_02',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_02_pkey'))
    )
    op.create_table('token_details_2026_01',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('generation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receipt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('token_details_created_by_fkey')),
    sa.ForeignKeyConstraint(['generation_id'], ['token_generations.id'], name=op.f('token_details_generation_id_fkey')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('token_details_updated_by_fkey')),
    sa.PrimaryKeyConstraint('id', 'created_at', name=op.f('token_details_2026_01_pkey'))
    )
    # ### end Alembic commands ###
