"""remove_wastage_reason

Revision ID: d12661aeccff
Revises: d437189dea9d
Create Date: 2026-05-10 00:44:35.792697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd12661aeccff'
down_revision: Union[str, Sequence[str], None] = 'd437189dea9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wastage_entries', 'reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wastage_entries', sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
