"""add_status_to_stock_ledger

Revision ID: d437189dea9d
Revises: 067ac375f988
Create Date: 2026-05-09 23:27:06.853887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd437189dea9d'
down_revision: Union[str, Sequence[str], None] = '067ac375f988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_ledger', sa.Column('status', sa.Integer(), server_default=sa.text('1'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_ledger', 'status')
    # ### end Alembic commands ###
