"""add_receipt_number_to_tokens

Revision ID: ee812d4dd204
Revises: ff2a20b3ec6b
Create Date: 2026-05-09 13:01:27.455591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee812d4dd204'
down_revision: Union[str, Sequence[str], None] = 'ff2a20b3ec6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_consumption_entries_usage_date'), table_name='consumption_entries')
    op.drop_index(op.f('idx_consumption_items_consumption_entry_id'), table_name='consumption_items')
    op.drop_index(op.f('idx_consumption_items_item_id'), table_name='consumption_items')
    op.drop_index(op.f('idx_purchase_entries_purchase_date'), table_name='purchase_entries')
    op.drop_index(op.f('idx_purchase_entries_user_id'), table_name='purchase_entries')
    op.drop_index(op.f('idx_purchase_entries_vendor_id'), table_name='purchase_entries')
    op.drop_index(op.f('idx_purchase_items_item_id'), table_name='purchase_items')
    op.drop_index(op.f('idx_purchase_items_purchase_entry_id'), table_name='purchase_items')
    op.drop_index(op.f('idx_stock_ledger_item_id'), table_name='stock_ledger')
    op.drop_index(op.f('idx_stock_ledger_txn_date'), table_name='stock_ledger')
    op.add_column('token_details', sa.Column('receipt_number', sa.Integer(), nullable=False))
    op.drop_index(op.f('idx_wastage_entries_wastage_date'), table_name='wastage_entries')
    op.drop_index(op.f('idx_wastage_items_item_id'), table_name='wastage_items')
    op.drop_index(op.f('idx_wastage_items_menu_item_id'), table_name='wastage_items')
    op.drop_index(op.f('idx_wastage_items_wastage_entry_id'), table_name='wastage_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_wastage_items_wastage_entry_id'), 'wastage_items', ['wastage_entry_id'], unique=False)
    op.create_index(op.f('idx_wastage_items_menu_item_id'), 'wastage_items', ['menu_item_id'], unique=False)
    op.create_index(op.f('idx_wastage_items_item_id'), 'wastage_items', ['item_id'], unique=False)
    op.create_index(op.f('idx_wastage_entries_wastage_date'), 'wastage_entries', ['wastage_date'], unique=False)
    op.drop_column('token_details', 'receipt_number')
    op.create_index(op.f('idx_stock_ledger_txn_date'), 'stock_ledger', ['txn_date'], unique=False)
    op.create_index(op.f('idx_stock_ledger_item_id'), 'stock_ledger', ['item_id'], unique=False)
    op.create_index(op.f('idx_purchase_items_purchase_entry_id'), 'purchase_items', ['purchase_entry_id'], unique=False)
    op.create_index(op.f('idx_purchase_items_item_id'), 'purchase_items', ['item_id'], unique=False)
    op.create_index(op.f('idx_purchase_entries_vendor_id'), 'purchase_entries', ['vendor_id'], unique=False)
    op.create_index(op.f('idx_purchase_entries_user_id'), 'purchase_entries', ['user_id'], unique=False)
    op.create_index(op.f('idx_purchase_entries_purchase_date'), 'purchase_entries', ['purchase_date'], unique=False)
    op.create_index(op.f('idx_consumption_items_item_id'), 'consumption_items', ['item_id'], unique=False)
    op.create_index(op.f('idx_consumption_items_consumption_entry_id'), 'consumption_items', ['consumption_entry_id'], unique=False)
    op.create_index(op.f('idx_consumption_entries_usage_date'), 'consumption_entries', ['usage_date'], unique=False)
    # ### end Alembic commands ###
