"""refactor_consumption_and_wastage_unified_v2

Revision ID: f003426e0e04
Revises: 019121aef244
Create Date: 2026-05-08 22:14:40.462736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f003426e0e04'
down_revision: Union[str, Sequence[str], None] = '019121aef244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'consumption_entries', 'financial_years', ['financial_year_id'], ['id'])
    op.create_foreign_key(None, 'daily_stock_summary', 'financial_years', ['financial_year_id'], ['id'])
    op.create_foreign_key(None, 'item_categories', 'financial_years', ['financial_year_id'], ['id'])
    op.create_foreign_key(None, 'item_types', 'financial_years', ['financial_year_id'], ['id'])
    op.create_foreign_key(None, 'items', 'financial_years', ['financial_year_id'], ['id'])
    op.create_foreign_key(None, 'menu_items', 'financial_years', ['financial_year_id'], ['id'])
    op.create_foreign_key(None, 'monthly_stock_summary', 'financial_years', ['financial_year_id'], ['id'])
    op.create_foreign_key(None, 'purchase_entries', 'financial_years', ['financial_year_id'], ['id'])
    op.create_foreign_key(None, 'stock_adjustments', 'financial_years', ['financial_year_id'], ['id'])
    op.create_foreign_key(None, 'stock_ledger', 'financial_years', ['financial_year_id'], ['id'])
    op.create_foreign_key(None, 'token_generations', 'financial_years', ['financial_year_id'], ['id'])
    op.create_foreign_key(None, 'units', 'financial_years', ['financial_year_id'], ['id'])
    op.create_foreign_key(None, 'vendor_payments', 'financial_years', ['financial_year_id'], ['id'])
    op.create_foreign_key(None, 'vendors', 'financial_years', ['financial_year_id'], ['id'])
    op.create_foreign_key(None, 'wastage_entries', 'financial_years', ['financial_year_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wastage_entries', type_='foreignkey')
    op.drop_constraint(None, 'vendors', type_='foreignkey')
    op.drop_constraint(None, 'vendor_payments', type_='foreignkey')
    op.drop_constraint(None, 'units', type_='foreignkey')
    op.drop_constraint(None, 'token_generations', type_='foreignkey')
    op.drop_constraint(None, 'stock_ledger', type_='foreignkey')
    op.drop_constraint(None, 'stock_adjustments', type_='foreignkey')
    op.drop_constraint(None, 'purchase_entries', type_='foreignkey')
    op.drop_constraint(None, 'monthly_stock_summary', type_='foreignkey')
    op.drop_constraint(None, 'menu_items', type_='foreignkey')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_constraint(None, 'item_types', type_='foreignkey')
    op.drop_constraint(None, 'item_categories', type_='foreignkey')
    op.drop_constraint(None, 'daily_stock_summary', type_='foreignkey')
    op.drop_constraint(None, 'consumption_entries', type_='foreignkey')
    # ### end Alembic commands ###
